config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'users#show'
  resources :user_languages, only: %i[new create]

  resources :user_words, only: %i[update]
  resources :courses, only: %i[index new create show] do
    resources :chapters, only: %i[new create show]
  end

  resources :words, param: :slug, only: %i[show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chapter.rb
# frozen_string_literal: true

class Chapter < Course
  belongs_to :course, foreign_key: :parent_id, inverse_of: :chapters, optional: true
  has_many :paragraphs, dependent: :destroy, foreign_key: :parent_id, inverse_of: :chapter

  acts_as_list scope: :course
end

app/models/course.rb
# frozen_string_literal: true

# Top level container model to contain learning materials
class Course < ApplicationRecord
  # TODO(Finn):
  # 1. Scope course to user
  # 2. Scope course to a language
  has_many :chapters, dependent: :destroy, foreign_key: :parent_id, inverse_of: :course

  acts_as_list
end

app/models/language.rb
# frozen_string_literal: true

class Language < ApplicationRecord
  has_many :words, dependent: :destroy
  has_many :user_languages, dependent: :destroy
  has_many :users, through: :user_languages

  scope :current, -> { joins(:user_languages).where(user_languages: { current: true }) }
end

app/models/paragraph.rb
# frozen_string_literal: true

class Paragraph < Chapter
  SPLIT_REGEX = /(\s*\n\s*){2,}/

  belongs_to :chapter, foreign_key: :parent_id, inverse_of: :paragraphs
  has_many :sentences, dependent: :destroy, inverse_of: :paragraph

  acts_as_list scope: :chapter

  delegate :course, to: :chapter, allow_nil: true

  def raw_text
    sentences.map(&:raw_text).join(' ')
  end
end

app/models/sentence.rb
# frozen_string_literal: true

# Contains the raw text and word associations for the paragraph, chapter and course
class Sentence < ApplicationRecord
  REGEX = /[—A-Z][^\.!?]*(?:\.{3}|[\.!?])/
  SPLIT_REGEX = /(?<=[?.!])/

  belongs_to :paragraph, inverse_of: :sentences
  has_many :sentence_words, dependent: :destroy, inverse_of: :sentence
  has_many :words, through: :sentence_words, inverse_of: :sentences

  acts_as_list scope: :paragraph
end

app/models/sentence_word.rb
# frozen_string_literal: true

class SentenceWord < ApplicationRecord
  belongs_to :sentence, inverse_of: :sentence_words
  belongs_to :word, inverse_of: :sentence_words
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_languages, dependent: :destroy
  has_many :languages, through: :user_languages
  has_many :user_words, dependent: :destroy
  has_many :words, through: :user_words
end

app/models/user_language.rb
# frozen_string_literal: true

class UserLanguage < ApplicationRecord
  belongs_to :user
  belongs_to :language

  validates :current, uniqueness: { scope: :user_id }, if: :current?
end

app/models/user_word.rb
# frozen_string_literal: true

class UserWord < ApplicationRecord
  STATUS_VALUES = {
    ignore: 0,
    not_learned: 1,
    recognised: 2,
    learned: 3
  }.freeze

  belongs_to :user
  belongs_to :word

  enum status: STATUS_VALUES
end

app/models/word.rb
# frozen_string_literal: true

class Word < ApplicationRecord
  FORBIDDEN_CHARACTERS = /[ ,!?()\[\]\n\r\t.]/
  REGEX = /[\p{L}\p{M}'-]+/

  attr_accessor :frequency

  belongs_to :language
  has_many :sentence_words, dependent: :destroy, inverse_of: :word
  has_many :sentences, through: :sentence_words, inverse_of: :words
  has_many :user_words, dependent: :destroy
  has_many :users, through: :user_words
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :sign_in_automatically! # TODO: Remove this line before going to production!
  before_action :authenticate_user!, unless: :devise_controller?

  helper_method :view_object

  def current_language
    current_user.languages.current.first
  end

  def view_object
    @view_object ||= {
      current_user: current_user.as_json.symbolize_keys,
      current_language: current_language.as_json&.symbolize_keys
    }
  end

  private

  def sign_in_automatically!
    sign_in User.first
  end
end

app/controllers/chapters_controller.rb
# frozen_string_literal: true

class ChaptersController < CoursesController
  before_action :find_course

  def show
    find_chapter
  end

  def new
    @chapter = @course.chapters.build
  end

  def create
    build_chapter
    if @chapter.valid?
      redirect_to course_path(@course)
    else
      render :new
    end
  end

  private

  def chapter_params
    params.require(:chapter).permit(:name)
  end

  def find_chapter
    @chapter = @course.chapters.find(params[:id])
  end

  def build_chapter
    @chapter = @course.chapters.build(chapter_params)
    Chapters::Ingest.call(@chapter, params[:raw_text])
  end
end

app/controllers/courses_controller.rb
# frozen_string_literal: true

# TODO(Finn): Before this ever goes to production this should all be scoped to the current user.
class CoursesController < ApplicationController
  def index
    @courses = Course.where(type: nil).all
  end

  def show
    find_course
    find_most_common_words
  end

  def new
    @course = Course.new
  end

  def create
    course = Course.create(course_params)
    redirect_to course_path(course)
  end

  private

  def course_params
    params.require(:course).permit(:name)
  end

  def find_course
    @course = Course.includes(chapters: { paragraphs: :sentences }).find(params[:course_id] || params[:id])
  end

  def find_most_common_words
    sentences = @course.chapters.flat_map(&:paragraphs).flat_map(&:sentences)

    # Brings back all the words in the course, sorted by frequency.
    # It returns a list of words with their id, name, and frequency.
    word_counts = Word.joins(:sentence_words)
                      .where(sentence_words: { sentence: sentences })
                      .group(:id)
                      .order('count_all DESC')
                      .count

    # Brings back all the words in the course, sorted by frequency.
    user_words = current_user.user_words
                             .includes(:word)
                             .joins(:word)
                             .where(word_id: word_counts.keys)
                             .where('(user_words.status != ? AND user_words.status != ?) OR user_words.status IS NULL',
                                    UserWord::STATUS_VALUES[:learned],
                                    UserWord::STATUS_VALUES[:ignore])
                             .each { |user_word| user_word.word.frequency = word_counts[user_word.word_id] }
    @most_common_words = user_words.sort_by { _1.word.frequency }.reverse.first(100)
  end
end

app/controllers/user_languages_controller.rb
# frozen_string_literal: true

class UserLanguagesController < ApplicationController
  def new
    @unlearned_languages = unlearned_languages.pluck(:name, :id)
  end

  def create
    @current_language = unlearned_languages.index_by(&:id)[params.dig(:user_language, :language).to_i]
    current_user.user_languages.create(language: @current_language, current: true)
  end

  private

  def unlearned_languages
    # TODO: Make this a single query
    @unlearned_languages = Language.select(:id, :name).where.not(id: current_user.languages.pluck(:id))
  end
end

app/controllers/user_words_controller.rb
# frozen_string_literal: true

class UserWordsController < ApplicationController
  def update
    user_word = current_user.user_words.find(params[:id])
    user_word.update(user_word_params)
    redirect_back(fallback_location: root_path)
  end

  private

  def user_word_params
    params.require(:user_word).permit(:status)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show; end
end

app/controllers/words_controller.rb
# frozen_string_literal: true

class WordsController < ApplicationController
  def show
    @word = Word.includes(:sentences, :user_words).find_by(name: params[:slug])
    @user_word = @word.user_words.find_by(user: current_user)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/chapters/new.html.erb
<%= form_for(@chapter, url: course_chapters_path(@course)) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field standard-padding">
    <textarea name="raw_text" id="raw-text" class='text-area-75-percent'></textarea>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chapters/show.html.erb
<h2><%=@chapter.name %></h2>

<% @chapter.paragraphs.each_with_index do |paragraph, index| %>
  <div>
    <% paragraph.sentences.each do |sentence| %>
      <% if sentence.raw_text.start_with?('-') %>
        <p><%= sentence.raw_text %></p>
      <% else %>
        <span><%= sentence.raw_text %></span>
      <% end %>
    <% end %>
  </div>
  <br/>
<% end %>

app/views/courses/index.html.erb
<h1>Courses</h1>

<%= link_to 'New Course', new_course_path %>

<% @courses.each do |course| %>
  <p>
    <%= link_to course.name, course_path(course) %>
  </p>
<% end %>

app/views/courses/new.html.erb
<%= form_for(@course) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/show.html.erb
<h1 class='mb-3'>
  <%= @course.name %>
</h1>

<h2 class='mb-3'>
  Chapters
  <%= link_to 'New Chapter', new_course_chapter_path(@course), class: 'btn btn-primary' %>
</h2>
<ol class='list-group list-group-numbered'>
  <% @course.chapters.each do |chapter| %>
    <li class='list-group-item'>
      <%= link_to chapter.name, course_chapter_path(@course, chapter) %>
    </li>
  <% end %>
</ol>

<br>
<br>

<h2>Most common words in the book</h2>

<table class='table table-striped table-hover'>
  <thead>
    <tr>
      <th scope='col'>Word</th>
      <th scope='col'>Frequency</th>
      <th scope='col'>Known</th>
    </tr>
  </thead>
  <tbody>
    <% @most_common_words.each do |user_word| %>
      <% word = user_word.word %>
      <tr>
        <td>
          <%= link_to(word.name, word_path(word.name)) %>
        </td>
        <td><%= word.frequency %></td>
        <td>
          <%= form_for(user_word) do |f| %>
            <%= f.collection_radio_buttons :status, UserWord::STATUS_VALUES.to_a, :first, :first %>

            <%= f.submit "save" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_navbar.html.erb
<%= link_to 'Courses', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WordTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render('layouts/navbar') if current_user %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/user_languages/create.html.erb
<%= turbo_frame_tag "new_user_language_form" do %>
  <h3>You are currently studying <%= @current_language.name %> </h3>
<% end %>

app/views/user_languages/new.html.erb
<%= turbo_frame_tag 'new_user_language_form' do %>
  <%= form_for UserLanguage.new(user_id: view_object.dig(current_user.id)) do |form| %>
    <%= form.select :language, @unlearned_languages %>
    <%= form.submit 'Start Learning' %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<% current_language = view_object[:current_language] %>

<h2>Welcome <%= view_object.dig(:current_user, :email) %></h2>
<% if current_language %>
  <h3>You are currently studying <%= view_object.dig(:current_language, :name) %> </h3>
<% else %>
  <%= turbo_frame_tag "new_user_language_form" do %>
    <div>
      <%= link_to "New Language", new_user_language_path %>
    </div>
  <% end %>
<% end %>

app/views/words/show.html.erb
<p><%= link_to "return", :back %></p>
<h1><%= @word.name %></h1>

<%= form_for(@user_word) do |f| %>
  <%= f.collection_radio_buttons :status, UserWord::STATUS_VALUES.to_a, :first, :first, {}, {class: 'form-check-input'} %>

  <%= f.submit "save", class: 'btn btn-primary' %>
<% end %>

<div class="row mt-3">
  <% @word.sentences.each do |sentence| %>
    <div class='col-sm-12 col-md-6 mb-3'>
      <div class="card">
        <div class="card-body">
          <p class="card-text"><%= sentence.raw_text %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>